# Generated by Django 2.0.5 on 2018-05-22 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("main", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "address1",
                    models.CharField(
                        max_length=60,
                        verbose_name="Address line 1",
                    ),
                ),
                (
                    "address2",
                    models.CharField(
                        max_length=60,
                        verbose_name="Address line 2",
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        max_length=12,
                        verbose_name="ZIP / Postal code",
                    ),
                ),
                ("city", models.CharField(max_length=60)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("uk", "United Kingdom"),
                            ("us", "United States of America"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
