# Generated by Django 2.0.5 on 2018-05-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0003_basket_basketline")]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address2",
            field=models.CharField(
                blank=True,
                max_length=60,
                verbose_name="Address line 2",
            ),
        )
    ]
