# Generated by Django 2.0.5 on 2018-06-06 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("main", "0005_auto_20180605_1835")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
