# Generated by Django 2.1 on 2018-08-17 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("main", "0006_auto_20180606_0801")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="last_spoken_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cs_chats",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
